import '../models/user.dart';
import '../models/help_request.dart';
import '../models/event.dart';
import '../models/chat.dart';

/// Mock Data Service
/// Provides sample data for testing the UI
class MockDataService {
  // Mock Users
  static final User currentUser = User(
    id: '1',
    name: 'Rahul Sharma',
    avatar: '👨',
    isVerified: true,
    city: 'Mumbai, Maharashtra',
    memberSince: DateTime(2024, 1, 1),
    peopleHelped: 42,
    hoursContributed: 128,
    impactScore: 850,
    avgResponseTime: 15,
    badges: ['First Help', 'Food Helper', 'Quick Responder', 'SEWADAAR'],
  );
  
  static final List<User> users = [
    User(id: '2', name: 'Amit Kumar', avatar: '👨', isVerified: true, peopleHelped: 67),
    User(id: '3', name: 'Priya Sharma', avatar: '👩', isVerified: false, peopleHelped: 58),
    User(id: '4', name: 'Medical Aid NGO', avatar: '🏥', isVerified: true, isNGO: true),
    User(id: '5', name: 'Hope Foundation', avatar: '💙', isVerified: true, isNGO: true),
    User(id: '6', name: 'Anonymous User', avatar: '👤', isVerified: true),
    User(id: '7', name: 'Sneha Reddy', avatar: '👩', isVerified: true, peopleHelped: 52),
    User(id: '8', name: 'Raj Mehta', avatar: '👨', isVerified: false, peopleHelped: 34),
    User(id: '9', name: 'Kavita Patel', avatar: '👩', isVerified: true, peopleHelped: 28),
    User(id: '10', name: 'Education For All', avatar: '📚', isVerified: true, isNGO: true),
    User(id: '11', name: 'Arjun Singh', avatar: '👨', isVerified: false, peopleHelped: 19),
    User(id: '12', name: 'Shelter First', avatar: '🏠', isVerified: true, isNGO: true),
  ];
  
  // Mock Help Requests (20+ varied posts)
  static List<HelpRequest> getHelpRequests() {
    return [
      HelpRequest(
        id: '1',
        user: users[0],
        category: 'Food',
        description: 'Elderly person near Station Road needs food and medical assistance. Very urgent situation.',
        location: 'Station Road, Andheri East, Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
        status: 'Needy',
        distance: 1.2,
        helpersCount: 0,
      ),
      HelpRequest(
        id: '2',
        user: users[1],
        category: 'Food',
        description: 'Successfully distributed 50 food packets to street vendors. Thank you to all volunteers who helped! 🙏',
        location: 'Dadar, Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 3)),
        status: 'Helped',
        distance: 2.8,
        helpersCount: 12,
      ),
      HelpRequest(
        id: '3',
        user: users[3],
        category: 'Medical',
        description: 'Free medical camp this Sunday at Powai Community Center. Bring your family for checkups!',
        location: 'Powai, Mumbai',
        imageUrl: 'assets/images/medical_help.png',
        timestamp: DateTime.now().subtract(const Duration(days: 2)),
        status: 'Upcoming',
        distance: 5.2,
        helpersCount: 8,
        hasPoll: true,
        poll: Poll(
          question: 'What time works best?',
          options: [
            PollOption(text: '9 AM - 12 PM', votes: 15),
            PollOption(text: '2 PM - 5 PM', votes: 23),
          ],
        ),
      ),
      HelpRequest(
        id: '4',
        user: users[2],
        category: 'Shelter',
        description: 'Family of 4 displaced due to building demolition. Need temporary housing urgently.',
        location: 'Bandra West, Mumbai',
        imageUrl: 'assets/images/winter_clothing.png',
        timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
        status: 'Needy',
        distance: 3.5,
        helpersCount: 2,
      ),
      HelpRequest(
        id: '5',
        user: users[6],
        category: 'Clothing',
        description: 'Collected 200+ winter jackets for distribution. Special thanks to all donors!',
        location: 'Kurla, Mumbai',
        imageUrl: 'assets/images/winter_clothing.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 8)),
        status: 'Helped',
        distance: 6.1,
        helpersCount: 18,
      ),
      HelpRequest(
        id: '6',
        user: users[9],
        category: 'Education',
        description: 'Free tuition classes for underprivileged children starting next week. Need volunteer teachers!',
        location: 'Goregaon, Mumbai',
        imageUrl: 'assets/images/education_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 12)),
        status: 'Upcoming',
        distance: 7.2,
        helpersCount: 5,
      ),
      HelpRequest(
        id: '7',
        user: users[7],
        category: 'Medical',
        description: 'Pregnant woman needs transportation to hospital. Available to help?',
        location: 'Malad, Mumbai',
        imageUrl: 'assets/images/medical_help.png',
        timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
        status: 'Needy',
        distance: 8.3,
        helpersCount: 1,
      ),
      HelpRequest(
        id: '8',
        user: users[4],
        category: 'Food',
        description: 'Daily meal distribution program starting this week. Volunteers needed for preparation and serving.',
        location: 'Andheri West, Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        status: 'Upcoming',
        distance: 2.1,
        helpersCount: 15,
        hasPoll: true,
        poll: Poll(
          question: 'Which days can you volunteer?',
          options: [
            PollOption(text: 'Weekdays', votes: 8),
            PollOption(text: 'Weekends', votes: 12),
            PollOption(text: 'Both', votes: 5),
          ],
        ),
      ),
      HelpRequest(
        id: '9',
        user: users[8],
        category: 'Financial',
        description: 'Small business owner affected by floods needs support to restart vegetable shop.',
        location: 'Borivali, Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        status: 'Needy',
        distance: 12.5,
        helpersCount: 0,
      ),
      HelpRequest(
        id: '10',
        user: users[10],
        category: 'Shelter',
        description: 'Renovated community shelter for 20 homeless people. Amazing teamwork by all volunteers!',
        location: 'Dharavi, Mumbai',
        imageUrl: 'assets/images/winter_clothing.png',
        timestamp: DateTime.now().subtract(const Duration(days: 3)),
        status: 'Helped',
        distance: 4.7,
        helpersCount: 25,
      ),
      HelpRequest(
        id: '11',
        user: users[5],
        category: 'Medical',
        description: 'Blood donation camp today at YMCA Hall. Your donation can save lives!',
        location: 'Churchgate, Mumbai',
        imageUrl: 'assets/images/medical_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 4)),
        status: 'Upcoming',
        distance: 9.8,
        helpersCount: 22,
      ),
      HelpRequest(
        id: '12',
        user: users[10],
        category: 'Education',
        description: 'Provided school supplies to 100 children. Thank you donors and volunteers!',
        location: 'Vile Parle, Mumbai',
        imageUrl: 'assets/images/education_help.png',
        timestamp: DateTime.now().subtract(const Duration(days: 2)),
        status: 'Helped',
        distance: 5.5,
        helpersCount: 8,
      ),
      HelpRequest(
        id: '13',
        user: users[2],
        category: 'Food',
        description: 'Daily worker injured and unable to work. Family needs groceries for this week.',
        location: 'Jogeshwari, Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 6)),
        status: 'Needy',
        distance: 6.8,
        helpersCount: 3,
      ),
      HelpRequest(
        id: '14',
        user: users[6],
        category: 'Clothing',
        description: 'Monsoon relief: Need raincoats and umbrellas for school children.',
        location: 'Kandivali, Mumbai',
        imageUrl: 'assets/images/winter_clothing.png',
        timestamp: DateTime.now().subtract(const Duration(minutes: 90)),
        status: 'Needy',
        distance: 10.2,
        helpersCount: 0,
      ),
      HelpRequest(
        id: '15',
        user: users[8],
        category: 'Medical',
        description: 'Successfully organized health checkup camp for 150 senior citizens. Grateful for doctor volunteers!',
        location: 'Chembur, Mumbai',
        imageUrl: 'assets/images/medical_help.png',
        timestamp: DateTime.now().subtract(const Duration(days: 5)),
        status: 'Helped',
        distance: 11.3,
        helpersCount: 14,
      ),
      HelpRequest(
        id: '16',
        user: users[7],
        category: 'Education',
        description: 'Computer literacy classes for women starting next month. Need laptop donations.',
        location: 'Bhandup, Mumbai',
        imageUrl: 'assets/images/education_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 10)),
        status: 'Upcoming',
        distance: 13.1,
        helpersCount: 6,
      ),
      HelpRequest(
        id: '17',
        user: users[9],
        category: 'Food',
        description: 'Running community kitchen for migrant workers. Need volunteers for weekend shifts.',
        location: 'Navi Mumbai',
        imageUrl: 'assets/images/food_help.png',
        timestamp: DateTime.now().subtract(const Duration(hours: 18)),
        status: 'Upcoming',
        distance: 15.7,
        helpersCount: 11,
      ),
      HelpRequest(
        id: '18',
        user: users[3],
        category: 'Shelter',
        description: 'Emergency accommodation needed for flood-affected families. Can accommodate 3-4 people.',
        location: 'Mulund, Mumbai',
        imageUrl: 'assets/images/winter_clothing.png',
        timestamp: DateTime.now().subtract(const Duration(minutes: 20)),
        status: 'Needy',
        distance: 14.2,
        helpersCount: 1,
      ),
    ];
  }
  
  // Mock Events (10+ varied events)
  static List<CommunityEvent> getEvents() {
    return [
      CommunityEvent(
        id: '1',
        title: 'Winter Clothing Drive',
        description: 'Help us collect warm clothes for those in need this winter',
        date: DateTime(2024, 12, 15),
        time: null,
        location: 'Various locations',
        volunteersNeeded: 234,
        volunteersRegistered: 234,
        imageUrl: 'assets/images/winter_clothing.png',
        category: 'clothing',
      ),
      CommunityEvent(
        id: '2',
        title: 'Community Food Drive',
        description: 'Join us in collecting and distributing food to those in need',
        date: DateTime(2024, 12, 15),
        time: '10:00 AM - 4:00 PM',
        location: 'Andheri Community Center',
        volunteersNeeded: 60,
        volunteersRegistered: 45,
        imageUrl: 'assets/images/food_help.png',
        isNGOVerified: true,
        category: 'food',
      ),
      CommunityEvent(
        id: '3',
        title: 'Beach Cleanup Day',
        description: 'Help us keep our beaches clean and beautiful',
        date: DateTime(2024, 12, 20),
        time: '7:00 AM - 11:00 AM',
        location: 'Juhu Beach, Mumbai',
        volunteersNeeded: 100,
        volunteersRegistered: 67,
        imageUrl: 'assets/images/beach_cleanup.png',
        isNGOVerified: false,
        category: 'other',
      ),
      CommunityEvent(
        id: '4',
        title: 'Medical Camp for Seniors',
        description: 'Free health checkups for senior citizens',
        date: DateTime(2024, 12, 18),
        time: '9:00 AM - 2:00 PM',
        location: 'Dadar Community Hall',
        volunteersNeeded: 25,
        volunteersRegistered: 22,
        imageUrl: 'assets/images/medical_help.png',
        isNGOVerified: true,
        category: 'medical',
      ),
      CommunityEvent(
        id: '5',
        title: 'Education Fair 2024',
        description: 'Career guidance and scholarship information for students',
        date: DateTime(2024, 12, 22),
        time: '10:00 AM - 5:00 PM',
        location: 'Bandra Auditorium',
        volunteersNeeded: 40,
        volunteersRegistered: 35,
        imageUrl: 'assets/images/education_help.png',
        isNGOVerified: true,
        category: 'education',
      ),
      CommunityEvent(
        id: '6',
        title: 'Homeless Shelter Renovation',
        description: 'Help us renovate and paint the community shelter',
        date: DateTime(2024, 12, 25),
        time: '8:00 AM - 6:00 PM',
        location: 'Kurla Shelter Home',
        volunteersNeeded: 50,
        volunteersRegistered: 48,
        imageUrl: 'assets/images/winter_clothing.png',
        isNGOVerified: false,
        category: 'shelter',
      ),
      CommunityEvent(
        id: '7',
        title: 'Tree Plantation Drive',
        description: 'Plant 500 trees to make our city greener',
        date: DateTime(2024, 12, 28),
        time: '6:00 AM - 10:00 AM',
        location: 'Aarey Colony, Mumbai',
        volunteersNeeded: 80,
        volunteersRegistered: 72,
        imageUrl: 'assets/images/beach_cleanup.png',
        isNGOVerified: true,
        category: 'other',
      ),
      CommunityEvent(
        id: '8',
        title: 'New Year Food Distribution',
        description: 'Celebrate New Year by feeding the homeless',
        date: DateTime(2025, 1, 1),
        time: '12:00 PM - 4:00 PM',
        location: 'Multiple locations citywide',
        volunteersNeeded: 120,
        volunteersRegistered: 95,
        imageUrl: 'assets/images/food_help.png',
        isNGOVerified: true,
        category: 'food',
      ),
      CommunityEvent(
        id: '9',
        title: 'Computer Training Workshop',
        description: 'Basic computer skills for unemployed youth',
        date: DateTime(2025, 1, 5),
        time: '2:00 PM - 5:00 PM',
        location: 'Powai Library',
        volunteersNeeded: 15,
        volunteersRegistered: 12,
        imageUrl: 'assets/images/education_help.png',
        isNGOVerified: false,
        category: 'education',
      ),
      CommunityEvent(
        id: '10',
        title: 'Blood Donation Camp',
        description: 'Donate blood and save lives',
        date: DateTime(2025, 1, 8),
        time: '9:00 AM - 3:00 PM',
        location: 'KEM Hospital, Parel',
        volunteersNeeded: 30,
        volunteersRegistered: 28,
        imageUrl: 'assets/images/medical_help.png',
        isNGOVerified: true,
        category: 'medical',
      ),
    ];
  }
  
  // Mock Chat Conversations
  static List<ChatConversation> getChatConversations() {
    return [
      ChatConversation(
        id: '1',
        otherUser: users[5],
        lastMessage: 'Thank you so much for your help!',
        lastMessageTime: DateTime.now().subtract(const Duration(minutes: 10)),
        unreadCount: 3,
        category: 'food help',
      ),
      ChatConversation(
        id: '2',
        otherUser: users[4],
        lastMessage: 'We appreciate your contribution',
        lastMessageTime: DateTime.now().subtract(const Duration(hours: 2)),
        unreadCount: 0,
        category: 'medical help',
      ),
      ChatConversation(
        id: '3',
        otherUser: users[5],
        lastMessage: 'When can we meet?',
        lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
        unreadCount: 1,
        category: 'clothing help',
      ),
      ChatConversation(
        id: '4',
        otherUser: users[6],
        lastMessage: 'The location works perfectly',
        lastMessageTime: DateTime.now().subtract(const Duration(hours: 5)),
        unreadCount: 0,
        category: 'shelter help',
      ),
      ChatConversation(
        id: '5',
        otherUser: users[8],
        lastMessage: 'I can help this weekend',
        lastMessageTime: DateTime.now().subtract(const Duration(days: 2)),
        unreadCount: 2,
        category: 'food help',
      ),
    ];
  }
  
  // Mock Chat Messages
  static List<ChatMessage> getChatMessages() {
    return [
      ChatMessage(
        id: '1',
        text: 'Hi! I saw your post about needing food assistance.',
        isSent: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 6)),
      ),
      ChatMessage(
        id: '2',
        text: 'Yes, thank you for reaching out!',
        isSent: true,
        timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
        hasReaction: true,
        reaction: '👍',
      ),
      ChatMessage(
        id: '3',
        text: 'I can bring some groceries today around 3 PM. Does that work?',
        isSent: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 4)),
      ),
      ChatMessage(
        id: '4',
        text: 'That would be wonderful! The location is near Station Road.',
        isSent: true,
        timestamp: DateTime.now().subtract(const Duration(minutes: 3)),
        hasReaction: true,
        reaction: '👍',
      ),
      ChatMessage(
        id: '5',
        text: 'Perfect! See you then 🙏',
        isSent: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 1)),
      ),
    ];
  }
  
  // Mock Impact Stats
  static Map<String, dynamic> getImpactStats() {
    return {
      'totalHelps': 1248,
      'activeVolunteers': 342,
      'hoursContributed': 4567,
      'citiesReached': 12,
      'monthlyTrend': [
        {'month': 'Jul', 'helps': 95},
        {'month': 'Aug', 'helps': 120},
        {'month': 'Sep', 'helps': 145},
        {'month': 'Oct', 'helps': 175},
        {'month': 'Nov', 'helps': 200},
        {'month': 'Dec', 'helps': 220},
      ],
      'categoryDistribution': {
        'Food': 450,
        'Medical': 280,
        'Shelter': 210,
        'Clothing': 180,
        'Education': 128,
      },
      'needDensity': {
        'Andheri': 45,
        'Bandra': 35,
        'Dadar': 55,
        'Powai': 30,
        'Thane': 35,
      },
    };
  }
  
  // Mock Leaderboard
  static List<Map<String, dynamic>> getLeaderboard() {
    return [
      {'user': User(id: '1', name: 'Priya Patel', avatar: '👩', peopleHelped: 67), 'rank': 1},
      {'user': User(id: '2', name: 'Amit Kumar', avatar: '👨', peopleHelped: 58), 'rank': 2},
      {'user': User(id: '3', name: 'Sneha Reddy', avatar: '👩', peopleHelped: 52), 'rank': 3},
      {'user': User(id: '4', name: 'Raj Sharma', avatar: '👨', peopleHelped: 48), 'rank': 4},
      {'user': User(id: '5', name: 'Maya Singh', avatar: '👩', peopleHelped: 45), 'rank': 5},
    ];
  }
  
  // Mock Success Stories
  static List<Map<String, String>> getSuccessStories() {
    return [
      {
        'text': 'Thanks to the HelpConnect community, I received warm meals for a week during difficult times. Forever grateful! 🙏',
        'author': 'Anonymous, Andheri',
        'time': '2 days ago',
      },
      {
        'text': 'Our NGO partnered with HelpConnect for winter clothing drive. We collected 500+ items in just one week!',
        'author': 'Hope Foundation',
        'time': '5 days ago',
      },
    ];
  }
}
